name: fypp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.4
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  http: ^1.2.2
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  image: "assets/image/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/splash.png
    - assets/image/1.png
    - assets/image/2.png
    - assets/image/3.png
    - assets/image/4.png
    - assets/image/5.png
    - assets/image/6.png
    - assets/image/gratitude.png
    - assets/image/week1.jpg
    - assets/image/week2.png
    - assets/image/week3.jpg
    - assets/image/week4.png
    - assets/image/week5.png
    - assets/image/week6.png
    - assets/image/week7.png
    - assets/image/week8.png
    - assets/image/bar.png
    - assets/image/chat.png
    - assets/image/planweek21.jpeg
    - assets/image/planweek22.jpeg
    - assets/image/planweek23.jpeg
    - assets/image/week31.png
    - assets/image/week32.png
    - assets/image/week33.png
    - assets/image/week34.png
    - assets/image/week35.png
    - assets/image/week41.png
    - assets/image/week42.png
    - assets/image/planweek51.jpeg
    - assets/image/planweek52.jpeg
    - assets/image/planweek53.jpeg
    - assets/image/planweek54.jpeg
    - assets/image/planweek6.png
    - assets/image/planweek7.jpeg
    - assets/image/planweek8.jpeg

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  leak_tracker: ^10.0.5
  material_color_utilities: ^0.12.0
  meta: ^1.15.0
  string_scanner: ^1.3.0
  vm_service: ^14.2.4
  web: ^1.0.0
